version: 0.1.{build}

branches:
  only:
    - master

image:
- Visual Studio 2017
- Visual Studio 2019

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake ..

build:
  project: build/ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal

test_script:
  - ctest -C %configuration%
